# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MsOCa6Ez6lw9-Ld950rVBLniPXtNaoG5
"""

def greet(hour):

    if hour < 18:
      return "good morning"
    else:
      return "good afternoon"

hour = int(input("Enter the hour (0-23): "))
print(greet(hour))