# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdbDj8LhwfqGO4fkkXjpR3p3b-ZgjiyO
"""

x = 0

while (x < 5):
  x += 1
  print (x)