# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_emxEjOEHYnvIx7L0ph8tGS0ispJy6k
"""

x = 0

for i in range (5):
  x += 1
  print (x)

